### ISSUE TITLE
fix delay

### ISSUE THREAD

**Issue by SeanArchibald** [SeanArchibald/scale-workshop#49]
Delay can't be enabled, and an error is thrown when delay is disabled:

```
Uncaught DOMException: Failed to execute 'disconnect' on 'AudioNode': the given destination is not connected.
    at Delay.disable (http://sevish.com/scaleworkshop/js/synth/Delay.js:13:15)
    at HTMLInputElement.<anonymous> (http://sevish.com/scaleworkshop/js/events.js:345:19)
    at HTMLInputElement.dispatch (http://sevish.com/scaleworkshop/inc/jquery-ui-1.12.1/external/jquery/jquery.js:5226:27)
    at HTMLInputElement.elemData.handle (http://sevish.com/scaleworkshop/inc/jquery-ui-1.12.1/external/jquery/jquery.js:4878:28)
```

**Comment by SeanArchibald** [comment]
added checks to make sure delay is inited first. this is now fixed for next release
